---
settings:
  name: Cloud Volumes Service for Google Cloud
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr
sidebar:
  entries:
  - title: 所有 Cloud Manager 文档
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: 适用于 Google Cloud 的 Cloud Volumes Service 文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 了解适用于 Google Cloud 的 Cloud Volumes Service
      url: "/concept-cvs-gcp.html"
    - title: 快速入门
      url: "/task-quick-start.html"
    - title: 设置 Google Cloud
      url: "/task-set-up-google-cloud.html"
    - title: 创建工作环境
      url: "/task-create-working-env.html"
  - title: 使用适用于 Google Cloud 的 Cloud Volumes Service
    entries:
    - title: 创建并挂载卷
      url: "/task-create-volumes.html"
    - title: 管理现有卷
      url: "/task-manage-volumes.html"
    - title: 管理云卷快照
      url: "/task-manage-snapshots.html"
    - title: 管理 Active Directory 配置
      url: "/task-manage-active-directory.html"
    - title: 删除 Cloud Volumes Service
      url: "/task-remove-working-env.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解适用于 Google Cloud 的 Cloud Volumes Service
      url: concept-cvs-gcp.html
    - title: 快速入门
      url: task-quick-start.html
  - title: 使用 Cloud Volumes Service
    links:
    - title: 创建卷
      url: task-create-volumes.html
    - title: 管理云卷快照
      url: task-manage-snapshots.html
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central 博客
      url: https://cloud.netapp.com/blog
    - title: 云网络研讨会
      url: https://cloud.netapp.com/events
product-family: {}
